stages:
  - test
  - security

before_script:
  - apt update -y && apt install python3 -y

include:
  - template: Security/SAST.gitlab-ci.yml

sast:
  before_script: []
  stage: security

run_unit_tests:
  stage: test
  script:
    - python3 -m unittest discover -s tests/ -p "*.py" -v