stages:
  - test
  - security
  - deploy
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  APPLICATION_VERSION: "v1"

before_script:
  - apt update -y && apt install python3 python3-pip -y
  - pip3 install --no-cache-dir -r requirements.txt

include:
  - template: Security/SAST.gitlab-ci.yml

sast:
  before_script: []
  stage: security

run_unit_tests:
  stage: test
  script:
    - python3 -m unittest discover -s tests/ -p "*.py" -v

build_gitlab_container_registry:
  stage: deploy
  tags:
    - alpine
  image: docker:20.10.10
  services:
    - docker:20.10.10-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
    ORCID_CLIENT_SECRET: ${ORCID_CLIENT_SECRET}
    REDIRECT_URI: ${ORCID_REDIRECT_URI}
  before_script: []
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - main

build_docker_hub_image:
  stage: build
  tags:
    - alpine
  image: docker:20.10.10
  services:
    - docker:20.10.10-dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:${APPLICATION_VERSION}" .
    - docker push "${CI_REGISTRY_IMAGE}:${APPLICATION_VERSION}"
  only:
    - main



