version: '3'
services:
  web:
    build: .
    ports:
      - "127.0.0.1:5100:5100"
    environment:
      - ORCID_CLIENT_ID=${ORCID_CLIENT_ID}
      - ORCID_CLIENT_SECRET=${ORCID_CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - SQLALCHEMY_DATABASE_URI=sqlite:////data/orcid_authorizations.db
    volumes:
      - db_data:/data
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit
    ports:
      - "127.0.0.1:8025:8025"
      - "127.0.0.1:1025:1025"

volumes:
  db_data: