version: '3'
services:
  web:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - ORCID_CLIENT_ID=${ORCID_CLIENT_ID}
      - ORCID_CLIENT_SECRET=${ORCID_CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit
    ports:
      - "127.0.0.1:8025:8025"
      - "127.0.0.1:1025:1025"